import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/incident.dart';

class ReportService {
  Future<void> generateIncidentReport(List<Incident> incidents) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        build: (context) => [
          pw.Header(level: 0, child: pw.Text('Sheltr.ai - Incident Report Summary')),
          pw.SizedBox(height: 20),
          pw.Table.fromTextArray(
            headers: ['Type', 'Severity', 'Status', 'Timestamp', 'Location'],
            data: incidents.map((i) => [
              i.type,
              i.severity?.toUpperCase() ?? 'PENDING',
              i.status,
              i.timestamp?.toString() ?? 'N/A',
              '${i.latitude?.toStringAsFixed(4)}, ${i.longitude?.toStringAsFixed(4)}'
            ]).toList(),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
            cellHeight: 30,
            cellAlignments: {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.center,
              2: pw.Alignment.center,
              3: pw.Alignment.centerLeft,
              4: pw.Alignment.centerLeft,
            },
          ),
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 20),
            child: pw.Text('Total Incidents: ${incidents.length}'),
          ),
          pw.Footer(
            margin: const pw.EdgeInsets.only(top: 50),
            leading: pw.Text('Generated by Sheltr.ai Staff Dashboard'),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'SheltrAI_Incident_Report.pdf',
    );
  }
}
